version: "3.8"

services:
  web-site:
    build: .
    container_name: safe_city
    volumes:
      - .:/app
    networks:
      - web_network
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production

networks:
  web_network:
    external: true
